require "tc_biff"
require "tc_ole"
require "tc_workbook"
require "tc_worksheet"
require "tc_format"
require "tc_formula"
require 'tc_chart'
require "tc_excel"
require "test_00_IEEE_double"
require 'test_01_add_worksheet'
require 'test_02_merge_formats'
require 'test_04_dimensions'
require 'test_05_rows'
require 'test_06_extsst'
require 'test_11_date_time'
require 'test_12_date_only'
require 'test_22_mso_drawing_group'
