#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
class ExcelFormulaParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    15,    49,    21,    23,    25,    27,    29,    18,    17,    48,
    19,     3,    16,   nil,     4,     6,     9,    10,    12,    13,
    14,    15,    21,    23,    25,    27,    29,    11,   nil,   nil,
    15,   nil,   nil,    16,   nil,     4,     6,     9,    10,    12,
    13,    14,    16,    15,     4,     6,     9,    10,    12,    13,
    14,   nil,    15,   nil,   nil,    16,   nil,     4,     6,     9,
    10,    12,    13,    14,    16,    15,     4,     6,     9,    10,
    12,    13,    14,   nil,    15,   nil,   nil,    16,   nil,     4,
     6,     9,    10,    12,    13,    14,    16,    15,     4,     6,
     9,    10,    12,    13,    14,   nil,    15,   nil,   nil,    16,
    35,     4,     6,     9,    10,    12,    13,    14,    16,    15,
     4,     6,     9,    10,    12,    13,    14,   nil,    15,   nil,
   nil,    16,   nil,     4,     6,     9,    10,    12,    13,    14,
    16,    15,     4,     6,     9,    10,    12,    13,    14,   nil,
    15,   nil,   nil,    16,   nil,     4,     6,     9,    10,    12,
    13,    14,    16,    15,     4,     6,     9,    10,    12,    13,
    14,   nil,    15,   nil,   nil,    16,   nil,     4,     6,     9,
    10,    12,    13,    14,    16,    15,     4,     6,     9,    10,
    12,    13,    14,   nil,   nil,   nil,   nil,    16,   nil,     4,
     6,     9,    10,    12,    13,    14,    19,    22,    24,    26,
    28,    30,   nil,   nil,   nil,   nil,   nil,   nil,    21,    23,
    25,    27,    29,   nil,    47,    19,    22,    24,    26,    28,
    30,    19,    22,    24,    26,    28,    30,    21,    23,    25,
    27,    29,    19,    21,    23,    25,    27,    29,    19,    22,
    24,    26,    28,    30,    21,    23,    25,    27,    29,    20,
    21,    23,    25,    27,    29,    19,    22,    24,    26,    28,
    30,    19,    22,    24,    26,   nil,   nil,    21,    23,    25,
    27,    29,   nil,    21,    23,    25,    27,    29,    19,    22,
    24,    26,   nil,    19,    22,    24,    26,    28,    30,   nil,
    21,    23,    25,    27,    29,    21,    23,    25,    27,    29,
    19,    22,    24,    26,    28,    30,    19,    22,   nil,   nil,
   nil,   nil,    21,    23,    25,    27,    29,   nil,    21,    23,
    25,    27,    29,    19,    22,    24,    26,    28,    30,    19,
    22,   nil,   nil,   nil,   nil,    21,    23,    25,    27,    29,
   nil,    21,    23,    25,    27,    29,    19,    22,    24,    26,
    28,    30,   nil,   nil,   nil,   nil,   nil,   nil,    21,    23,
    25,    27,    29 ]

racc_action_check = [
    30,    34,    31,    31,    31,    31,    31,     4,     3,    34,
    36,     1,    30,   nil,    30,    30,    30,    30,    30,    30,
    30,     2,    36,    36,    36,    36,    36,     2,   nil,   nil,
    48,   nil,   nil,     2,   nil,     2,     2,     2,     2,     2,
     2,     2,    48,    29,    48,    48,    48,    48,    48,    48,
    48,   nil,    28,   nil,   nil,    29,   nil,    29,    29,    29,
    29,    29,    29,    29,    28,    15,    28,    28,    28,    28,
    28,    28,    28,   nil,    16,   nil,   nil,    15,   nil,    15,
    15,    15,    15,    15,    15,    15,    16,    18,    16,    16,
    16,    16,    16,    16,    16,   nil,    19,   nil,   nil,    18,
    18,    18,    18,    18,    18,    18,    18,    18,    19,    21,
    19,    19,    19,    19,    19,    19,    19,   nil,    22,   nil,
   nil,    21,   nil,    21,    21,    21,    21,    21,    21,    21,
    22,    23,    22,    22,    22,    22,    22,    22,    22,   nil,
    24,   nil,   nil,    23,   nil,    23,    23,    23,    23,    23,
    23,    23,    24,    25,    24,    24,    24,    24,    24,    24,
    24,   nil,    26,   nil,   nil,    25,   nil,    25,    25,    25,
    25,    25,    25,    25,    26,    27,    26,    26,    26,    26,
    26,    26,    26,   nil,   nil,   nil,   nil,    27,   nil,    27,
    27,    27,    27,    27,    27,    27,    32,    32,    32,    32,
    32,    32,   nil,   nil,   nil,   nil,   nil,   nil,    32,    32,
    32,    32,    32,   nil,    32,    43,    43,    43,    43,    43,
    43,    45,    45,    45,    45,    45,    45,    43,    43,    43,
    43,    43,    38,    45,    45,    45,    45,    45,     5,     5,
     5,     5,     5,     5,    38,    38,    38,    38,    38,     5,
     5,     5,     5,     5,     5,    33,    33,    33,    33,    33,
    33,    44,    44,    44,    44,   nil,   nil,    33,    33,    33,
    33,    33,   nil,    44,    44,    44,    44,    44,    46,    46,
    46,    46,   nil,    37,    37,    37,    37,    37,    37,   nil,
    46,    46,    46,    46,    46,    37,    37,    37,    37,    37,
    39,    39,    39,    39,    39,    39,    40,    40,   nil,   nil,
   nil,   nil,    39,    39,    39,    39,    39,   nil,    40,    40,
    40,    40,    40,    41,    41,    41,    41,    41,    41,    42,
    42,   nil,   nil,   nil,   nil,    41,    41,    41,    41,    41,
   nil,    42,    42,    42,    42,    42,    50,    50,    50,    50,
    50,    50,   nil,   nil,   nil,   nil,   nil,   nil,    50,    50,
    50,    50,    50 ]

racc_action_pointer = [
   nil,    11,    13,     8,   -13,   235,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    57,    66,   nil,    79,    88,
   nil,   101,   110,   123,   132,   145,   154,   167,    44,    35,
    -8,   -13,   193,   252,   -20,   nil,     7,   280,   229,   297,
   303,   320,   326,   212,   258,   218,   275,   nil,    22,   nil,
   343 ]

racc_action_default = [
    -2,   -31,    -1,   -31,   -19,   -31,   -20,   -16,   -26,   -21,
   -22,    -4,   -23,   -24,   -25,   -31,   -31,    51,   -31,   -31,
    -3,   -31,   -31,   -31,   -31,   -31,   -31,   -31,   -31,   -31,
   -31,   -18,   -31,   -29,   -31,   -28,    -9,   -11,   -10,   -12,
    -7,   -13,    -8,   -14,    -5,   -15,    -6,   -17,   -31,   -27,
   -30 ]

racc_goto_table = [
     5,     1,     2,    34,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    31,    32,   nil,    33,    36,   nil,    37,
    38,    39,    40,    41,    42,    43,    44,    45,    46,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    50 ]

racc_goto_check = [
     3,     1,     2,     6,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     3,     3,   nil,     3,     3,   nil,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,     1,     2,    -2,   nil,   nil,   -15 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     7,     8,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 31, :_reduce_1,
  0, 32, :_reduce_none,
  3, 32, :_reduce_none,
  2, 32, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  3, 33, :_reduce_none,
  1, 33, :_reduce_none,
  3, 34, :_reduce_none,
  2, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  4, 35, :_reduce_none,
  3, 35, :_reduce_none,
  1, 36, :_reduce_none,
  3, 36, :_reduce_none ]

racc_reduce_n = 31

racc_shift_n = 51

racc_token_table = {
  false => 0,
  :error => 1,
  :UMINUS => 2,
  "^" => 3,
  "&" => 4,
  "*" => 5,
  "/" => 6,
  "+" => 7,
  "-" => 8,
  "<" => 9,
  ">" => 10,
  "<=" => 11,
  ">=" => 12,
  "<>" => 13,
  :EOL => 14,
  :LT => 15,
  :GT => 16,
  :LE => 17,
  :GE => 18,
  :NE => 19,
  "(" => 20,
  ")" => 21,
  :FUNC => 22,
  :NUMBER => 23,
  :STRING => 24,
  :REF2D => 25,
  :REF3D => 26,
  :RANGE2D => 27,
  :RANGE3D => 28,
  "," => 29 }

racc_nt_base = 30

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "UMINUS",
  "\"^\"",
  "\"&\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"<>\"",
  "EOL",
  "LT",
  "GT",
  "LE",
  "GE",
  "NE",
  "\"(\"",
  "\")\"",
  "FUNC",
  "NUMBER",
  "STRING",
  "REF2D",
  "REF3D",
  "RANGE2D",
  "RANGE3D",
  "\",\"",
  "$start",
  "formula",
  "expr_list",
  "expr",
  "primary",
  "funcall",
  "args" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'excelformula.y', 13)
  def _reduce_1(val, _values, result)
     puts 'Syntax OK.'
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ExcelFormulaParser
