#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
class ExcelFormulaParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    16,    52,    25,    27,    29,    31,    33,    20,    19,     3,
   nil,    53,    22,    18,   nil,     4,     5,     6,     8,    12,
    13,    14,    15,    17,    16,    25,    27,    29,    31,    33,
   nil,    10,   nil,   nil,   nil,    16,   nil,    18,   nil,     4,
     5,     6,     8,    12,    13,    14,    15,    17,    18,    16,
     4,     5,     6,     8,    12,    13,    14,    15,    17,   nil,
    16,   nil,    18,   nil,     4,     5,     6,     8,    12,    13,
    14,    15,    17,    18,    16,     4,     5,     6,     8,    12,
    13,    14,    15,    17,   nil,    16,   nil,    18,   nil,     4,
     5,     6,     8,    12,    13,    14,    15,    17,    18,    16,
     4,     5,     6,     8,    12,    13,    14,    15,    17,   nil,
    16,   nil,    18,    36,     4,     5,     6,     8,    12,    13,
    14,    15,    17,    18,    16,     4,     5,     6,     8,    12,
    13,    14,    15,    17,   nil,    16,   nil,    18,   nil,     4,
     5,     6,     8,    12,    13,    14,    15,    17,    18,    16,
     4,     5,     6,     8,    12,    13,    14,    15,    17,   nil,
    16,   nil,    18,   nil,     4,     5,     6,     8,    12,    13,
    14,    15,    17,    18,    16,     4,     5,     6,     8,    12,
    13,    14,    15,    17,   nil,    16,   nil,    18,   nil,     4,
     5,     6,     8,    12,    13,    14,    15,    17,    18,    16,
     4,     5,     6,     8,    12,    13,    14,    15,    17,   nil,
    16,   nil,    18,   nil,     4,     5,     6,     8,    12,    13,
    14,    15,    17,    18,   nil,     4,     5,     6,     8,    12,
    13,    14,    15,    17,    22,    23,    26,    28,    30,    32,
   nil,   nil,   nil,   nil,   nil,    21,   nil,    25,    27,    29,
    31,    33,   nil,    51,    22,    23,    26,    28,    30,    32,
    22,    23,    26,    28,   nil,   nil,   nil,    25,    27,    29,
    31,    33,   nil,    25,    27,    29,    31,    33,    22,    23,
    26,    28,   nil,   nil,   nil,    22,    23,    26,    28,    30,
    32,    25,    27,    29,    31,    33,    21,    24,    25,    27,
    29,    31,    33,    22,    23,    26,    28,    30,    32,   nil,
   nil,   nil,   nil,   nil,    21,   nil,    25,    27,    29,    31,
    33,    22,    23,    26,    28,    30,    32,   nil,   nil,   nil,
   nil,   nil,    21,   nil,    25,    27,    29,    31,    33,    22,
    23,    26,    28,    30,    32,    22,   nil,   nil,   nil,   nil,
    21,   nil,    25,    27,    29,    31,    33,   nil,    25,    27,
    29,    31,    33,    22,    23,    26,    28,    30,    32,    22,
    23,   nil,   nil,   nil,    21,   nil,    25,    27,    29,    31,
    33,   nil,    25,    27,    29,    31,    33,    22,    23,    26,
    28,    30,    32,    22,    23,   nil,   nil,   nil,    21,   nil,
    25,    27,    29,    31,    33,   nil,    25,    27,    29,    31,
    33,    22,    23,    26,    28,    30,    32,   nil,   nil,   nil,
   nil,   nil,    21,   nil,    25,    27,    29,    31,    33,    22,
    23,    26,    28,    30,    32,   nil,   nil,   nil,   nil,   nil,
    21,   nil,    25,    27,    29,    31,    33 ]

racc_action_check = [
    33,    38,    34,    34,    34,    34,    34,     4,     3,     1,
   nil,    38,    40,    33,   nil,    33,    33,    33,    33,    33,
    33,    33,    33,    33,     2,    40,    40,    40,    40,    40,
   nil,     2,   nil,   nil,   nil,    53,   nil,     2,   nil,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    53,    32,
    53,    53,    53,    53,    53,    53,    53,    53,    53,   nil,
    31,   nil,    32,   nil,    32,    32,    32,    32,    32,    32,
    32,    32,    32,    31,    16,    31,    31,    31,    31,    31,
    31,    31,    31,    31,   nil,    18,   nil,    16,   nil,    16,
    16,    16,    16,    16,    16,    16,    16,    16,    18,    20,
    18,    18,    18,    18,    18,    18,    18,    18,    18,   nil,
    21,   nil,    20,    20,    20,    20,    20,    20,    20,    20,
    20,    20,    20,    21,    22,    21,    21,    21,    21,    21,
    21,    21,    21,    21,   nil,    23,   nil,    22,   nil,    22,
    22,    22,    22,    22,    22,    22,    22,    22,    23,    25,
    23,    23,    23,    23,    23,    23,    23,    23,    23,   nil,
    26,   nil,    25,   nil,    25,    25,    25,    25,    25,    25,
    25,    25,    25,    26,    27,    26,    26,    26,    26,    26,
    26,    26,    26,    26,   nil,    28,   nil,    27,   nil,    27,
    27,    27,    27,    27,    27,    27,    27,    27,    28,    29,
    28,    28,    28,    28,    28,    28,    28,    28,    28,   nil,
    30,   nil,    29,   nil,    29,    29,    29,    29,    29,    29,
    29,    29,    29,    30,   nil,    30,    30,    30,    30,    30,
    30,    30,    30,    30,    35,    35,    35,    35,    35,    35,
   nil,   nil,   nil,   nil,   nil,    35,   nil,    35,    35,    35,
    35,    35,   nil,    35,    39,    39,    39,    39,    39,    39,
    47,    47,    47,    47,   nil,   nil,   nil,    39,    39,    39,
    39,    39,   nil,    47,    47,    47,    47,    47,    49,    49,
    49,    49,   nil,   nil,   nil,     7,     7,     7,     7,     7,
     7,    49,    49,    49,    49,    49,     7,     7,     7,     7,
     7,     7,     7,    37,    37,    37,    37,    37,    37,   nil,
   nil,   nil,   nil,   nil,    37,   nil,    37,    37,    37,    37,
    37,    48,    48,    48,    48,    48,    48,   nil,   nil,   nil,
   nil,   nil,    48,   nil,    48,    48,    48,    48,    48,    50,
    50,    50,    50,    50,    50,    41,   nil,   nil,   nil,   nil,
    50,   nil,    50,    50,    50,    50,    50,   nil,    41,    41,
    41,    41,    41,    42,    42,    42,    42,    42,    42,    43,
    43,   nil,   nil,   nil,    42,   nil,    42,    42,    42,    42,
    42,   nil,    43,    43,    43,    43,    43,    44,    44,    44,
    44,    44,    44,    45,    45,   nil,   nil,   nil,    44,   nil,
    44,    44,    44,    44,    44,   nil,    45,    45,    45,    45,
    45,    46,    46,    46,    46,    46,    46,   nil,   nil,   nil,
   nil,   nil,    46,   nil,    46,    46,    46,    46,    46,    54,
    54,    54,    54,    54,    54,   nil,   nil,   nil,   nil,   nil,
    54,   nil,    54,    54,    54,    54,    54 ]

racc_action_pointer = [
   nil,     9,    16,     8,   -14,   nil,   nil,   282,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    66,   nil,    77,   nil,
    91,   102,   116,   127,   nil,   141,   152,   166,   177,   191,
   202,    52,    41,    -8,   -14,   231,   nil,   300,   -21,   251,
     9,   342,   360,   366,   384,   390,   408,   257,   318,   275,
   336,   nil,   nil,    27,   426 ]

racc_action_default = [
    -2,   -34,    -1,   -34,   -20,   -21,   -22,   -34,   -23,   -17,
    -4,   -29,   -24,   -25,   -26,   -27,   -34,   -28,   -34,    55,
   -34,   -34,   -34,   -34,    -3,   -34,   -34,   -34,   -34,   -34,
   -34,   -34,   -34,   -34,   -19,   -34,   -31,   -32,   -34,   -16,
    -9,   -10,   -11,    -7,   -12,    -8,   -13,    -5,   -14,    -6,
   -15,   -18,   -30,   -34,   -33 ]

racc_goto_table = [
     7,     1,     2,    38,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    34,   nil,    35,   nil,    37,    39,
    40,    41,   nil,    42,    43,    44,    45,    46,    47,    48,
    49,    50,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    54 ]

racc_goto_check = [
     3,     1,     2,     6,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     3,   nil,     3,   nil,     3,     3,
     3,     3,   nil,     3,     3,     3,     3,     3,     3,     3,
     3,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     3 ]

racc_goto_pointer = [
   nil,     1,     2,    -2,   nil,   nil,   -17 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     9,    11,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 34, :_reduce_none,
  0, 35, :_reduce_2,
  3, 35, :_reduce_3,
  2, 35, :_reduce_none,
  3, 36, :_reduce_5,
  3, 36, :_reduce_6,
  3, 36, :_reduce_7,
  3, 36, :_reduce_8,
  3, 36, :_reduce_9,
  3, 36, :_reduce_10,
  3, 36, :_reduce_11,
  3, 36, :_reduce_12,
  3, 36, :_reduce_13,
  3, 36, :_reduce_14,
  3, 36, :_reduce_15,
  3, 36, :_reduce_16,
  1, 36, :_reduce_none,
  3, 37, :_reduce_18,
  2, 37, :_reduce_19,
  1, 37, :_reduce_none,
  1, 37, :_reduce_21,
  1, 37, :_reduce_22,
  1, 37, :_reduce_23,
  1, 37, :_reduce_24,
  1, 37, :_reduce_25,
  1, 37, :_reduce_26,
  1, 37, :_reduce_27,
  1, 37, :_reduce_28,
  1, 37, :_reduce_none,
  4, 38, :_reduce_30,
  3, 38, :_reduce_31,
  1, 39, :_reduce_32,
  3, 39, :_reduce_33 ]

racc_reduce_n = 34

racc_shift_n = 55

racc_token_table = {
  false => 0,
  :error => 1,
  :UMINUS => 2,
  "^" => 3,
  "&" => 4,
  "*" => 5,
  "/" => 6,
  "+" => 7,
  "-" => 8,
  "<" => 9,
  ">" => 10,
  "<=" => 11,
  ">=" => 12,
  "<>" => 13,
  "=" => 14,
  :EOL => 15,
  :LT => 16,
  :GT => 17,
  :LE => 18,
  :GE => 19,
  :NE => 20,
  "(" => 21,
  ")" => 22,
  :FUNC => 23,
  :NUMBER => 24,
  :STRING => 25,
  :REF2D => 26,
  :REF3D => 27,
  :RANGE2D => 28,
  :RANGE3D => 29,
  :TRUE => 30,
  :FALSE => 31,
  "," => 32 }

racc_nt_base = 33

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "UMINUS",
  "\"^\"",
  "\"&\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"<>\"",
  "\"=\"",
  "EOL",
  "LT",
  "GT",
  "LE",
  "GE",
  "NE",
  "\"(\"",
  "\")\"",
  "FUNC",
  "NUMBER",
  "STRING",
  "REF2D",
  "REF3D",
  "RANGE2D",
  "RANGE3D",
  "TRUE",
  "FALSE",
  "\",\"",
  "$start",
  "formula",
  "expr_list",
  "expr",
  "primary",
  "funcall",
  "args" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'excelformula.y', 20)
  def _reduce_2(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 21)
  def _reduce_3(val, _values, result)
     result.push val[1], '_arg', '1'
    result
  end
.,.,

# reduce 4 omitted

module_eval(<<'.,.,', 'excelformula.y', 24)
  def _reduce_5(val, _values, result)
     result = [ val[0], val[2], 'ptgAdd' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 25)
  def _reduce_6(val, _values, result)
     result = [ val[0], val[2], 'ptgSub' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 26)
  def _reduce_7(val, _values, result)
     result = [ val[0], val[2], 'ptgMul' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 27)
  def _reduce_8(val, _values, result)
     result = [ val[0], val[2], 'ptgDiv' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 28)
  def _reduce_9(val, _values, result)
     result = [ val[0], val[2], 'ptgPower' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 29)
  def _reduce_10(val, _values, result)
     result = [ val[0], val[2], 'ptgConcat' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 30)
  def _reduce_11(val, _values, result)
     result = [ val[0], val[2], 'ptgLT' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 31)
  def _reduce_12(val, _values, result)
     result = [ val[0], val[2], 'ptgGT' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 32)
  def _reduce_13(val, _values, result)
     result = [ val[0], val[2], 'ptgLE' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 33)
  def _reduce_14(val, _values, result)
     result = [ val[0], val[2], 'ptgGE' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 34)
  def _reduce_15(val, _values, result)
     result = [ val[0], val[2], 'ptgNE' ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 35)
  def _reduce_16(val, _values, result)
     result = [ val[0], val[2], 'ptgEQ' ]
    result
  end
.,.,

# reduce 17 omitted

module_eval(<<'.,.,', 'excelformula.y', 38)
  def _reduce_18(val, _values, result)
     result = [ val[1], '_arg', '1', 'ptgParen']
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 39)
  def _reduce_19(val, _values, result)
     result = [ '_num', '-1', val[1], 'ptgMul' ]
    result
  end
.,.,

# reduce 20 omitted

module_eval(<<'.,.,', 'excelformula.y', 41)
  def _reduce_21(val, _values, result)
     result = [ '_num',     val[0] ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 42)
  def _reduce_22(val, _values, result)
     result = [ '_str',     val[0] ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 43)
  def _reduce_23(val, _values, result)
     result = [ '_ref2d',   val[0] ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 44)
  def _reduce_24(val, _values, result)
     result = [ '_ref3d',   val[0] ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 45)
  def _reduce_25(val, _values, result)
     result = [ '_range2d', val[0] ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 46)
  def _reduce_26(val, _values, result)
     result = [ '_range3d', val[0] ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 47)
  def _reduce_27(val, _values, result)
     result = [ 'ptgBool',  '1'    ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 48)
  def _reduce_28(val, _values, result)
     result = [ 'ptgBool',  '0'    ]
    result
  end
.,.,

# reduce 29 omitted

module_eval(<<'.,.,', 'excelformula.y', 51)
  def _reduce_30(val, _values, result)
     result = [ '_class', val[0], val[2], '_arg', val[2].size.to_s, '_func', val[0] ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 52)
  def _reduce_31(val, _values, result)
     result = [ '_func', val[0] ]
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 54)
  def _reduce_32(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'excelformula.y', 55)
  def _reduce_33(val, _values, result)
     result.push val[2]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ExcelFormulaParser


class ExcelFormulaParserError < StandardError; end

class Node

   def exec_list(nodes)
      v = nil
      nodes.each { |i| v = i.evaluate }
      v
   end

   def excelformulaparser_error(msg)
      raise ExcelFormulaParserError,
               "in #{fname}:#{lineno}: #{msg}"
   end

end

class RootNode < Node

   def initialize(tree)
      @tree = tree
   end

   def evaluate
      exec_list @tree
   end

end


class FuncallNode < Node

   def initialize(func, args)
      @func = func
      @args = args
   end

   def evaluate
      arg = @args.collect {|i| i.evaluate }
      out = []
      arg.each { |i| o.push i }
      o.push @func
      p o
   end

end

class NumberNode < Node

   def initialize(val)
      @val = val
   end

   def evaluate
      p @val
   end

end

class OperateNode < Node

   def initialize(op, left, right)
      @op = op
      @left = left
      @right = right
   end

   def evaluate
      o = []
      o.push @left
      o.push @right
      o.push @op
      p o
   end
end
